### PR TITLE
Changes for Jekyll 3.x

### LINKED ISSUE #144: Changes for Jekyll 3.x
Jekyll 3.x has some changes with Jekyll 2.x. This is a list of some:
- Jekyll 3.x does not support anymore permalinks. We must remove it.
- Jekyll 3.x does not support anymore Pygments as highlighter. Instead of pygments, we must use Rouge.
- Jekyll 3.x does not support anymore redcarpet. Instead of redcarpet, we must use kramdown as markdown engine.

### PR DESCRIPTION
**Pull request by JuanjoSalvador**
No more warnings on email when I update my web.

This fix #144

### CODE REVIEW

**Comment by pauldotknopf** [comment]
MERGE THIS IN!

**Comment by karlhorky** [comment]
@mdo does this look ok? Can it be merged?

**Comment by JuanjoSalvador** [comment]
Hey @karlhorky, I'm using this changes for my web since I pulled this and everthing is OK :)

**Comment by karlhorky** [comment]
Yep, it's working for me too, as long as I add the two jekyll gem dependencies to the config file.

``` yaml
gems: [jekyll-paginate, jekyll-gist]
```

~~But I think fixing the dependencies can be done with a separate pull request, since it doesn't strictly concern Jekyll 3.~~

Hm, maybe that's not entirely accurate that Jekyll 3 didn't cause this issue with the dependencies. It says on the [pagination docs page](https://jekyllrb.com/docs/pagination/):

> For Jekyll 3, include the jekyll-paginate plugin in your Gemfile

In any case, would be good to get a response from one of the maintainers like @mdo so that some (or both) of these changes can be merged.

**Comment by mdo** [comment]
Fix coming in #258.

**Pull request closed without merging**
